name: Train-Pipeline

on:
  push:
  pull_request:
    branches:
    #  layers
    - branch_01
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

jobs:
  test_train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # CORRECTED: Updated to v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@v5 # CORRECTED: Updated to v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Test files
        run: |
          pytest test_train.py

  # You can uncomment this job if you need code style checking
  # check_python_code_style:
  #   runs-on: ubuntu-latest
  #   steps:
  #     ...

  train_pipeline:
      runs-on: ubuntu-latest
      needs: [test_train]
      steps:
          - uses: actions/checkout@v4 # CORRECTED: Updated to v4
            with:
              fetch-depth: 0

          - name: Set up Python 3.9
            uses: actions/setup-python@v5 # CORRECTED: Updated to v5
            with:
                python-version: 3.9

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          - name: Train Model
            run: |
              python train.py 

  build_image:
    runs-on: ubuntu-latest
    needs: [train_pipeline]
    steps:
      - uses: actions/checkout@v4 # CORRECTED: Updated to v4

      - name: Set up Docker Buildx # CORRECTED: Required for build-push-action
        uses: docker/setup-buildx-action@v3

      - name: Docker Login # CORRECTED: Use secure login action
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }} # Use your PAT here

      - name: Build and Push Docker image # CORRECTED: Combine build and push for reliability
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest